create edition hack1;

ALTER SESSION SET EDITION = hack1;

ALTER TABLE T_TEST ADD (
	DEPT VARCHAR2(20) ); 


INSERT INTO V_TEST(ID,NAME,SAL,ADDRESS,DEPT) VALUES(1001, 'P1', 1000, 'CHENNAI','ENGG');
INSERT INTO V_TEST(ID,NAME,SAL,ADDRESS,DEPT) VALUES(1002, 'P2', 1000, 'CHENNAI','ENGG');
INSERT INTO V_TEST(ID,NAME,SAL,ADDRESS,DEPT) VALUES(1003, 'P3', 1000, 'CHENNAI','ENGG');
INSERT INTO V_TEST(ID,NAME,SAL,ADDRESS,DEPT) VALUES(1004, 'P4', 1000, 'CHENNAI','ENGG');
INSERT INTO V_TEST(ID,NAME,SAL,ADDRESS,DEPT) VALUES(1005, 'P5', 1000, 'CHENNAI','ENGG');
INSERT INTO V_TEST(ID,NAME,SAL,ADDRESS,DEPT) VALUES(1006, 'P6', 1000, 'CHENNAI','ENGG');
INSERT INTO V_TEST(ID,NAME,SAL,ADDRESS,DEPT) VALUES(1007, 'P7', 1000, 'CHENNAI','ENGG');
INSERT INTO V_TEST(ID,NAME,SAL,ADDRESS,DEPT) VALUES(1008, 'P8', 1000, 'CHENNAI','ENGG');
INSERT INTO V_TEST(ID,NAME,SAL,ADDRESS,DEPT) VALUES(1009, 'P9', 1000, 'CHENNAI','ENGG');
INSERT INTO V_TEST(ID,NAME,SAL,ADDRESS,DEPT) VALUES(1011, 'P10', 1000, 'CHENNAI','ENGG');
INSERT INTO V_TEST(ID,NAME,SAL,ADDRESS,DEPT) VALUES(1011, 'P11', 1000, 'CHENNAI','ENGG');


CREATE OR REPLACE EDITIONING VIEW V_TEST AS
	SELECT id, name, sal, address, dept FROM T_TEST;

CREATE OR REPLACE T_TEST_FXD
BEFORE INSERT OR UPDATE
ON T_TEST
FOR EACH ROW
FORWARD CROSSEDITION
DISABLE
BEGIN
:NEW.DEPT := TRIM(:NEW.DEPT);
END T_TEST_FXD;
/
ALTER TRIGGER T_TEST_FXD ENABLE
/



