ALTER SESSION SET EDITION = ora$base;

SELECT SYS_CONTEXT('USERENV', 'CURRENT_EDITION_NAME') FROM DUAL;

CREATE OR REPLACE PROCEDURE say_hello
IS
l_edition VARCHAR2(30);
BEGIN
SELECT SYS_CONTEXT('USERENV', 'CURRENT_EDITION_NAME')
INTO l_edition
FROM DUAL;
DBMS_OUTPUT.PUT_LINE('Chennai hackathon. This is from '||l_edition);
END;
/


ALTER SESSION SET EDITION = proctest;

SELECT SYS_CONTEXT('USERENV', 'CURRENT_EDITION_NAME') FROM DUAL;


CREATE OR REPLACE PROCEDURE say_hello
IS
l_edition VARCHAR2(30);
BEGIN
SELECT SYS_CONTEXT('USERENV', 'CURRENT_EDITION_NAME')
INTO l_edition
FROM DUAL;
DBMS_OUTPUT.PUT_LINE('Hello from hackathon. This code is changed. current edition is '||l_edition||'.');
END;
/

